package ru.randomwords
import android.os.Bundle
import android.os.CountDownTimer
import android.os.Handler
import android.os.Looper
import android.graphics.Color
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import kotlin.math.max
import kotlin.random.Random
class ChallengeActivity:AppCompatActivity(){
 private lateinit var root:LinearLayout;private lateinit var editor:EditText;private lateinit var wordsBox:TextView;private lateinit var info:TextView
 private var config=ChallengeConfig();private var words=mutableListOf<String>();private var seconds=0;private var timer:CountDownTimer?=null;private val h=Handler(Looper.getMainLooper());private var reset=false;private var shield=false;private var blindHidden=false;private var lastSentenceWord=""
 override fun onCreate(b:Bundle?){super.onCreate(b);setup()}
 private fun setup(){
  root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,20);setBackgroundColor(Color.parseColor(Ui.BG))};val sc=ScrollView(this);sc.addView(root);setContentView(sc)
  addTitle("НОВОЕ ИСПЫТАНИЕ","Здесь случайность превращается в сюжет.")
  label("КОЛИЧЕСТВО СЛОВ");val count=Spinner(this);count.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("1","2","3","5","7","10"));count.setSelection(2);root.addView(count,lp(52))
  label("ЦЕЛЬ");val goal=Spinner(this);goal.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("100 слов","200 слов","300 слов","2 минуты","5 минут","10 минут","∞ без цели"));root.addView(goal,lp(52))
  label("СЛОЖНОСТЬ ПАУЗЫ");val idle=Spinner(this);idle.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("Легко — 6 сек","Норма — 5 сек","Жёстко — 4 сек","Безумие — 3 сек"));idle.setSelection(1);root.addView(idle,lp(52))
  val blind=CheckBox(this).apply{text="Слепой режим — слова исчезают через 5 секунд"};val chaos=CheckBox(this).apply{text="Хаос — новое слово каждые 45 секунд"};val boss=CheckBox(this).apply{text="Слово-босс — последнее слово даёт бонус"};val repeat=CheckBox(this).apply{text="Повторить предыдущий набор"};val duel=CheckBox(this).apply{text="Дуэль с рекордом — нужно побить лучший счёт"};val last=CheckBox(this).apply{text="Последнее предложение — финальный обязательный удар"};listOf(blind,chaos,boss,repeat,duel,last).forEach{root.addView(it)}
  root.addView(Button(this).apply{text="✦  НАЧАТЬ ИСПЫТАНИЕ";setOnClickListener{val c=count.selectedItem.toString().toInt();val g=goal.selectedItem.toString();val gt=when{g.startsWith("∞")->GoalType.ENDLESS;g.contains("мин")->GoalType.TIME;else->GoalType.WORDS};val gv=when{g.startsWith("100")->100;g.startsWith("200")->200;g.startsWith("300")->300;g.startsWith("2")->120;g.startsWith("5")->300;g.startsWith("10")->600;else->0};val sec=when(idle.selectedItemPosition){0->6;1->5;2->4;else->3};config=ChallengeConfig(c,gt,gv,sec,blind.isChecked,chaos.isChecked,boss.isChecked,repeat.isChecked,false,duel.isChecked,last.isChecked);startChallenge()}},lp(58))
  root.addView(Button(this).apply{text="☼  ЕЖЕДНЕВНЫЙ ВЫЗОВ";setOnClickListener{config=ChallengeConfig(3,GoalType.WORDS,100,5,false,false,true,false,true,false,true);startChallenge()}},lp(58))
 }
 private fun startChallenge(){
  root.removeAllViews();seconds=0;shield=false;blindHidden=false;lastSentenceWord="";val bank=Store.words(this);val seed=if(config.daily)java.text.SimpleDateFormat("yyyyMMdd",java.util.Locale.US).format(java.util.Date()).hashCode() else System.currentTimeMillis().toInt();val rnd=Random(seed);words=(if(config.repeatWords&&lastWords.isNotEmpty())lastWords.toMutableList()else bank.shuffled(rnd).take(config.count).toMutableList());if(config.boss&&words.isNotEmpty())words[words.lastIndex]=words.last()+" ★";lastWords=words.toMutableList()
  addTitle(if(config.daily)"ЕЖЕДНЕВНЫЙ ВЫЗОВ" else "ПИШИ","Пауза дольше "+config.idleSeconds+" сек — текст будет сброшен.")
  wordsBox=TextView(this).apply{text=words.joinToString("   ·   ");gravity=Gravity.CENTER;Ui.text(this,22,Ui.GOLD);background=Ui.bg(Ui.CARD,22f);setPadding(18,22,18,22);setOnClickListener{revealWords()}};root.addView(wordsBox,lp(110))
  info=TextView(this).apply{gravity=Gravity.CENTER;Ui.text(this,13,Ui.MUTED)};root.addView(info,lp(42))
  editor=EditText(this).apply{hint="Начни писать здесь…";gravity=Gravity.TOP;setTextColor(Color.parseColor(Ui.TEXT));setHintTextColor(Color.parseColor(Ui.MUTED));textSize=18f;setPadding(18,18,18,18);background=Ui.bg("#171920",20f);minHeight=360};root.addView(editor,LinearLayout.LayoutParams(-1,0,1f))
  root.addView(Button(this).apply{text="СОХРАНИТЬ ТЕКСТ";setOnClickListener{finishSuccess()}},lp(58))
  editor.addTextChangedListener(object:android.text.TextWatcher{override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int){};override fun onTextChanged(s:CharSequence?,st:Int,b:Int,c:Int){if(reset)return;armIdle();updateInfo();if(goalReached())finishSuccess() };override fun afterTextChanged(s:android.text.Editable?){}})
  editor.requestFocus();armIdle();startGoalTimer();if(config.blind)h.postDelayed({if(!isFinishing&&!editor.text.isBlank()){blindHidden=true;wordsBox.text="•••  СЛОВА СКРЫТЫ  •••"}},5000)
 }
 private fun revealWords(){if(!config.blind||!blindHidden)return;wordsBox.text=words.joinToString("   ·   ");h.postDelayed({if(!isFinishing){blindHidden=true;wordsBox.text="•••  СЛОВА СКРЫТЫ  •••"}},2000)}
 private fun updateInfo(){val wc=countWords(editor.text.toString());val missing=words.count{!containsWord(editor.text.toString(),it.replace(" ★",""))};info.text="Слов: "+wc+"  •  Осталось: "+missing+"  •  "+if(config.goalType==GoalType.TIME)"Время: "+format(config.goal-seconds)else if(config.goalType==GoalType.WORDS)"Цель: "+config.goal else "Без цели"}
 private fun armIdle(){h.removeCallbacksAndMessages(null);h.postDelayed({if(editor.text.isNotBlank())timeout()},config.idleSeconds*1000L)}
 private fun timeout(){\n        Store.breakStreak(this)val saved=editor.text.toString();reset=true;editor.setText("");reset=false;timer?.cancel();if(shield){AlertDialog.Builder(this).setTitle("Пауза поймала тебя").setMessage("Последний шанс уже использован.").setPositiveButton("Новые слова"){_,_->startChallenge()}.show();return};AlertDialog.Builder(this).setTitle("Пауза поймала тебя").setMessage("Тишина превысила "+config.idleSeconds+" секунд. Текст удалён.").setNegativeButton("Начать заново"){_,_->startChallenge()}.setPositiveButton("Последний шанс"){_,_->shield=true;editor.setText(saved);editor.setSelection(editor.text.length);armIdle()}.show()}
 private fun startGoalTimer(){timer?.cancel();timer=object:CountDownTimer(if(config.goalType==GoalType.TIME)config.goal*1000L else 24*60*60*1000L,1000){override fun onTick(ms:Long){seconds++;if(config.chaos&&seconds%45==0)addChaosWord();updateInfo()};override fun onFinish(){if(config.goalType==GoalType.TIME)finishSuccess()}}.start()}
 private fun addChaosWord(){val extra=Store.words(this).filterNot{words.contains(it)}.shuffled().firstOrNull()?:return;words.add(extra);if(!blindHidden)wordsBox.text=words.joinToString("   ·   ");Toast.makeText(this,"ХАОС: добавлено слово «"+extra+"»",Toast.LENGTH_SHORT).show()}
 private fun goalReached():Boolean{if(config.goalType!=GoalType.WORDS)return false;val basic=countWords(editor.text.toString())>=config.goal&&words.all{containsWord(editor.text.toString(),it.replace(" ★",""))};if(!basic)return false;if(config.lastSentence&&lastSentenceWord.isBlank()){lastSentenceWord=Store.words(this).filterNot{words.contains(it)}.shuffled().firstOrNull()?:"финал";words.add(lastSentenceWord);if(!blindHidden)wordsBox.text=words.joinToString("   ·   ");Toast.makeText(this,"ФИНАЛ: последнее предложение должно содержать «"+lastSentenceWord+"»",Toast.LENGTH_LONG).show();return false};return true}
 private fun finishSuccess(){if(!goalReached()&&config.goalType==GoalType.WORDS)return;if(editor.text.isBlank())return;timer?.cancel();h.removeCallbacksAndMessages(null);val text=editor.text.toString();if(!words.all{containsWord(text,it.replace(" ★",""))}){AlertDialog.Builder(this).setTitle("Не все слова использованы").setMessage("Сначала используй каждое ключевое слово.").setPositiveButton("Продолжить",null).show();return};if(config.lastSentence&&lastSentenceWord.isNotBlank()){val finalSentence=text.split(Regex("[.!?]+")).map{it.trim()}.filter{it.isNotBlank()}.lastOrNull()?.lowercase()?:"";if(!finalSentence.contains(lastSentenceWord.lowercase())){AlertDialog.Builder(this).setTitle("Финальный удар не принят").setMessage("Последнее предложение должно содержать слово «"+lastSentenceWord+"».").setPositiveButton("Продолжить",null).show();return}}
  val wc=countWords(text);val base=wc+words.size*10+(if(config.boss)25 else 0);val difficulty=when(config.idleSeconds){3->2.0;4->1.5;5->1.25;else->1.0};val combo=1.0+minOf(1.0,Store.streak(this)*0.1);val score=max(1,(base*difficulty*combo).toInt());if(config.duel&&score<=Store.best(this)){AlertDialog.Builder(this).setTitle("Рекорд устоял").setMessage("Твой счёт: "+score+"\nЛучший: "+Store.best(this)+"\nПопробуй ещё раз.").setPositiveButton("Ещё раз"){_,_->startChallenge()}.setNegativeButton("В меню"){_,_->finish()}.show();return}
  Store.registerSuccess(this,score);if(wc>=100)Store.unlock(this,"100 слов");if(config.idleSeconds<=4)Store.unlock(this,"Без паузы");if(Store.total(this)>=10)Store.unlock(this,"10 текстов");if(config.daily)Store.unlock(this,"Ежедневный вызов");if(config.duel)Store.unlock(this,"Победа над рекордом");if(config.lastSentence)Store.unlock(this,"Финальный удар");val d=Draft(System.currentTimeMillis(),"Без названия",text,words,System.currentTimeMillis(),seconds,score);Store.saveDraft(this,d);showAnalysis(d,score,wc)
 }
 private fun showAnalysis(d:Draft,score:Int,wc:Int){val sentences=d.text.split(Regex("[.!?]+")).map{it.trim()}.filter{it.isNotBlank()};val chars=d.text.count{it.isLetter()};val avg=if(wc==0)0.0 else chars.toDouble()/wc;val longest=sentences.maxByOrNull{it.length}?.length?:0;val message="Счёт: "+score+"\nСлов: "+wc+"\nПредложений: "+sentences.size+"\nСредняя длина слова: "+String.format(java.util.Locale.US,"%.1f",avg)+"\nСамое длинное предложение: "+longest+" символов\nКомбо: x"+String.format(java.util.Locale.US,"%.1f",1.0+minOf(1.0,Store.streak(this)*0.1));val e=EditText(this);e.hint="Название текста";AlertDialog.Builder(this).setTitle("Текст завершён").setMessage(message).setView(e).setPositiveButton("В библиотеку"){_,_->d.title=if(e.text.isBlank())"Текст "+java.text.SimpleDateFormat("dd.MM.yyyy",java.util.Locale.getDefault()).format(java.util.Date())else e.text.toString();Store.saveDraft(this,d);finish()}.setNeutralButton("Сохранить без названия"){_,_->finish()}.show()}
 private fun containsWord(text:String,w:String)=text.lowercase().replace(Regex("[^\\p{L}\\s]")," ").split(Regex("\\s+")).contains(w.lowercase())
 private fun countWords(s:String)=s.trim().let{if(it.isEmpty())0 else it.split(Regex("\\s+")).size}
 private fun format(s:Int)="%02d:%02d".format(max(0,s)/60,max(0,s)%60)
 private fun addTitle(a:String,b:String){root.addView(TextView(this).apply{text=a;Ui.text(this,25);setTypeface(typeface,1);setPadding(0,0,0,6)},lp(40));root.addView(TextView(this).apply{text=b;Ui.text(this,13,Ui.MUTED);setPadding(0,0,0,12)},lp(42))}
 private fun label(t:String){root.addView(TextView(this).apply{text=t;Ui.text(this,11,Ui.MUTED);setPadding(4,12,4,4)})}
 private fun lp(h:Int)=LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)}
 companion object{var lastWords=listOf<String>()}
}
